import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import NavBar from "@/components/NavBar";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <head>
        <link
          rel="icon"
          type="image/png"
          href="/icons/favicon-96x96.png"
          sizes="96x96"
        />
        <link rel="icon" type="image/svg+xml" href="/icons/favicon.svg" />
        <link rel="shortcut icon" href="/icons/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/icons/apple-touch-icon.png"
        />
        <meta name="apple-mobile-web-app-title" content="Coco's Blog" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body className={`${pretendard.className} font-sans`}>
        <NavBar />
        <main className="max-w-4xl mx-auto p-4">{children}</main>
        <footer className="border-t mt-8">
          <div className="max-w-4xl mx-auto p-4 text-center text-gray-600 text-sm">
            © {new Date().getFullYear()} Coco&apos;s Blog. 대충 right에 관련된
            말.
          </div>
        </footer>
      </body>
    </html>
  );
}
