import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import localFont from "next/font/local";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className={`${pretendard.className} font-sans`}>
        <header className="border-b">
          <div className="max-w-4xl mx-auto p-4">
            <nav className="flex justify-between items-center">
              <Link href="/" className="text-2xl font-bold">
                My Blog
              </Link>
              <div className="space-x-4">
                <Link href="/posts" className="hover:text-gray-600">
                  Posts
                </Link>
                <Link href="/about" className="hover:text-gray-600">
                  About
                </Link>
              </div>
            </nav>
          </div>
        </header>
        <main className="max-w-4xl mx-auto p-4">{children}</main>
        <footer className="border-t mt-8">
          <div className="max-w-4xl mx-auto p-4 text-center text-gray-600">
            © {new Date().getFullYear()} My Blog. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
